language: python
python:
  - "2.7"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -y install acl

install: pip install -r ./test-requirements.txt && pip install -r ./requirements.txt

script: make check

notifications:
  email: false
