language: python
python:
  - "2.7"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -y install python-nose python-dev build-essential git make acl

install: sudo make install

script: sudo make check

notifications:
  email: false
