language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get -y install acl netcat python-pyxattr

install: pip install -r ./test-requirements.txt && pip install -r ./requirements.txt

script: make ci-check

notifications:
  email: false
